export enum AppRoute {
  Home = '/',
  Register = '/register',
  Login = '/login',
  MyBooks = '/mybooks',
  Ranking = '/ranking',
  Author = '/author',
  Book = '/book/:id',
  BooksCatalog = '/bookscatalog',
  ProvidersCatalog = '/providerscatalog',
  AddNewBook = '/addnewbook',
  AddReview = '/addreview/:id',
  WojtekPage = '/wojtek',
  testPage = '/test',
}
